<? /** @var \omSocialLogin\providers\Google $this */ ?>
<table class="form-table">
	<tr>
		<td colspan="2">
			<h3>
				<? include \omSocialLogin\omSocialLogin::dir('/img/' . strtolower($this->getName()) . '.svg') ?>
				Google
			</h3>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Enable', SL) ?></th>
		<td>
			<label for="google_enable">
				<input name="google_enable" type="checkbox" id="google_enable"
				       value="1" <?php checked(true, $this->options->enable); ?> />
				<?php _e('enable', SL) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row">
			<label for="google_strategy_client_id"><?php _e('Client ID', SL) ?></label>
		</th>
		<td>
			<input name="google_strategy[client_id]" type="text" id="google_strategy_client_id"
			       value="<?= esc_attr($this->options->getStrategy('client_id')) ?>"
			       class="large-text"/>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row">
			<label for="google_strategy_client_secret"><?php _e('Client secret', SL) ?></label>
		</th>
		<td>
			<input name="google_strategy[client_secret]" type="text" id="google_strategy_client_secret"
			       value="<?= esc_attr($this->options->getStrategy('client_secret')) ?>"
			       class="large-text"/>

			<p class="description">
				<? _e('Register here:', SL) ?>
				<a href="https://code.google.com/apis/console/" target="_blank">https://code.google.com/apis/console/</a>
			</p>
		</td>
	</tr>

	<td>

	</td>
</table>
