<? /** @var \omSocialLogin\providers\Facebook $this */ ?>
<table class="form-table">
	<tr>
		<td colspan="2">
			<h3>

				<svg version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="64px" height="64px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve">
					<path class="facebook social-icon" id="Facebook" d="M38.078,22.431c0,2.268,0,12.391,0,12.391H29v15.152h9.078V95h18.649V49.975h12.513
					c0,0,1.172-7.265,1.74-15.209c-1.629,0-14.183,0-14.183,0s0-8.815,0-10.36c0-1.548,2.033-3.631,4.043-3.631c2.006,0,6.239,0,10.16,0
					c0-2.063,0-9.191,0-15.774c-5.235,0-11.189,0-13.814,0C37.617,5,38.078,20.167,38.078,22.431z"/>
				</svg>

				Facebook
			</h3>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Enable', SL) ?></th>
		<td>
			<label for="facebook_enable">
				<input name="facebook_enable" type="checkbox" id="facebook_enable"
				       value="1" <?php checked(true, $this->options->enable); ?> />
				<?php _e('enable', SL) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row">
			<label for="facebook_strategy_app_id"><?php _e('App ID', SL) ?></label>
		</th>
		<td>
			<input name="facebook_strategy[app_id]" type="text" id="facebook_strategy_app_id"
			       value="<?= esc_attr($this->options->getStrategy('app_id')) ?>"
			       class="large-text"/>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row">
			<label for="facebook_strategy_app_secret"><?php _e('App Secret', SL) ?></label>
		</th>
		<td>
			<input name="facebook_strategy[app_secret]" type="text" id="facebook_strategy_app_secret"
			       value="<?= esc_attr($this->options->getStrategy('app_secret')) ?>"
			       class="large-text"/>

			<p class="description"><? _e('Register here:', SL) ?>
				<a href="https://developers.facebook.com/apps/" target="_blank">https://developers.facebook.com/apps/</a>
			</p>
		</td>
	</tr>

</table>