<div class="omLoginButtons">
	<div class="wrapper">
		<h4><? _e('Login with:', SL) ?></h4>
		<? foreach ($providers as $name => $provider) {
			/** @var \omSocialLogin\providers\IProvider $provider */
			if (!$provider->isEnable()) continue;
			$namel = strtolower($name) ?>
			<a href="/auth/<?= $namel ?>"><img src="<?= \omSocialLogin\omSocialLogin::uri('/img/' . $namel . '.png') ?>"
			                                   alt="<?= $namel ?>"/><span class="screen-reader-text"><?= $name ?></span></a>
		<? } ?>
	</div>
</div>