<? /** @var \omSocialLogin\providers\Github $this */ ?>
<table class="form-table">
	<tr>
		<td colspan="2">
			<h3>
				<? include \omSocialLogin\omSocialLogin::dir('/img/' . strtolower($this->getName()) . '.svg') ?>
				Github
			</h3>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Enable', SL) ?></th>
		<td>
			<label for="github_enable">
				<input name="github_enable" type="checkbox" id="github_enable"
				       value="1" <?php checked(true, $this->options->enable); ?> />
				<?php _e('enable', SL) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row">
			<label for="github_strategy_client_id"><?php _e('Client ID', SL) ?></label>
		</th>
		<td>
			<input name="github_strategy[client_id]" type="text" id="github_strategy_client_id"
			       value="<?= esc_attr($this->options->getStrategy('client_id')) ?>"
			       class="large-text"/>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row">
			<label for="github_strategy_app_secret"><?php _e('Client secret', SL) ?></label>
		</th>
		<td>
			<input name="github_strategy[client_secret]" type="text" id="github_strategy_client_secret"
			       value="<?= esc_attr($this->options->getStrategy('client_secret')) ?>"
			       class="large-text"/>

			<p class="description"><? _e('Register here:', SL)?> <a href="https://github.com/settings/applications/new" target="_blank">https://github.com/settings/applications/new</a>
			</p>
		</td>
	</tr>

</table>