<h3><? _e('Social connection', SL) ?></h3>

<style type="text/css">

	.not-connected .button {
		height: auto;
	}

	.not-connected svg {
		vertical-align: middle;
		width: 16px;
		height: 16px;
	}

	.connected ul {
		border: 1px solid #ddd;
		float: left;
		margin-right: 1em;
		min-width: 220px;
		-moz-border-radius: 2px;
		-ms-border-radius: 2px;
		border-radius: 2px;
		background: #fefefe;
	}

	.connected ul .title {
		border-bottom: 1px solid #ddd;
		background: #eee;
		margin-bottom: 5px;
	}

	.connected ul li {
		padding: 4px 1em;
		margin: 0;
	}

	.connected th {
		line-height: 42px;
	}

	.connected .action {
		text-align: center;
		padding: 8px 0;
	}

	.connected svg {
		vertical-align: middle;
		width: 16px;
		height: 16px;
	}
</style>

<? ob_start();
$empty = true; ?>
<table class="form-table not-connected">
	<tr>
		<th><? _e('Connect your account with', SL) ?></th>
		<td>
			<? foreach ($this->providers as $name => $provider) {
				/** @var \omSocialLogin\providers\IProvider $provider */
				if (!$provider->isEnable()) continue; // skip disabled providers
				if (isset($connected[$name])) continue; // skip connected providers
				$empty = false;
				?>
				<a href="/auth/<?= strtolower($name) ?>?connect=1" class="button">
					<? include \omSocialLogin\omSocialLogin::dir('/img/' . strtolower($name) . '.svg') ?>
					<span><? _e('Connect with', SL) ?> <?= $name ?></span>
				</a>
			<? } ?>

		</td>
	</tr>
</table>
<?
$not_connected = ob_get_contents();
ob_clean();
if (!$empty) echo $not_connected;
?>

<? if ($connected) { ?>

	<table class="form-table connected">
		<tr>
			<th>
				<? _e('Conected with', SL) ?>
			</th>

			<td>
				<? foreach ($connected as $name => $connect) { ?>
					<? $info = \omSocialLogin\UserMeta::getInfo($user->ID, $name); ?>
					<ul>
						<li class="title">
							<? include \omSocialLogin\omSocialLogin::dir('/img/' . strtolower($name) . '.svg') ?>
							<span><?= $name ?></span>
						</li>
						<?
						if (isset($info['image'])) {
							echo sprintf(
								'<li style="text-align: center"><img src = "%s" width = "50" height = "50" alt = "" /></li>',
								$info['image']
							);
						}

						if (isset($info['name'])) {
							echo sprintf('<li><strong>%s</strong>: %s</li> ', __('Name', SL), $info['name']);
						}
						if (isset($info['nickname'])) {
							echo sprintf('<li><strong>%s</strong>: %s</li> ', __('Nickname', SL), $info['nickname']);
						}
						if (isset($info['email'])) {
							echo sprintf('<li><a href="mailto:%s">%s</a></li> ', $info['email'], $info['email']);
						}

						?>

						<? if ($creatorProviderName !== $name) { ?>
							<li class="action">
								<button type="submit" name="disconnect" class="button" value="<?= esc_attr($name) ?>">
									<? _e('Remove connection', SL) ?>
								</button>
							</li>
						<? } ?>
					</ul>
				<? } ?>
			</td>
		</tr>
	</table>

<? } ?>